sudo: false
language: node_js
node_js:
- "8"
env:
- DATABASE_URL=postgres://postgres@localhost:5432/unleash_test TEST_DATABASE_URL=postgres://postgres@localhost:5432/unleash_test
before_script:
- psql -c 'create database unleash_test;' -U postgres
script:
- yarn
- yarn run test:coverage
after_success:
- yarn run test:coverage-report
notifications:
  slack:
    secure: MroremSKwtQkwPbrXjgs9hIqKTCDKk7bAIXXzjcS6wXC9uRaFgwFaW8oO3vBxtWa4BL44EQBLE/rboWgqFER62+XgXNgEqGZqrcJHJvby4r+dUNMPI64OZvWdIiydIYxLo8C1C4x5PqBup0xuLq8h/SBnNvA2NLgkjuvzOi+v/Q=
addons:
  postgresql: "9.4"
cache:
  yarn: true
